const template = [
  "MMMMMMMMMWWWWWWWMMMMMMMMM",
  "PPPPPPWWDDDDDDDDDWWPPPPPP",
  "PPPPPPWDDDDDDDDDDDWPPPPPP",
  "PPPPPPWDDDWWWWWDDDWPPPPPP",
  "PPPPPMWDWWMMMMMWWDWMPPPPP",
  "PPPPPMWHMMMMMMMMMHWMPPPPP",
  "PPPPPMMHMMMMMMMMMHMMPPPPP",
  "PPPPMHHHMMMMMMMMMHHHMPPPP",
  "PPMMHHPPPPPPPPPPPPPHHMMPP",
  "PMMMHPPPPPPPPPPPPPPPHMMMP",
  "MMMHPTTTTTTTTTTTTTTTPHMMM",
  "MMMHPTTCCCCCCCCCCCTTPHMMM",
  "MMMHPTTCCCCCCCCCCCTTPHMMM",
  "MMGHPPPPCCCCCCCCCPPPPHGMM",
  "PPGPPPPPCCCCCCCCCPPPPPGPP",
  "PPGPPPPPCCCCCCCCCPPPPPGPP",
  "MMGHPPPPCCCCCCCCCPPPPHGMM",
  "MMMHPTTCCCCCCCCCCCTTPHMMM",
  "MMMHPTTCCCCCCCCCCCTTPHMMM",
  "MMMHPTTTTTTTTTTTTTTTPHMMM",
  "PMMMHPPPPPPPPPPPPPPPHMMMP",
  "PPMMHHPPPPPPPPPPPPPHHMMPP",
  "PPPMMHHHMMMMMMMMMHHHMMPPP",
  "PPPPPMMHMMMMMMMMMHMMPPPPP",
  "PPPPPMHMMMMMMMMMMMHMMPPPP",
];
template.forEach((l, i) => {
  if(l.length !== 25) console.error(`Row ${i} is ${l.length}`);
});
console.log(JSON.stringify(template, null, 2));
